<RockSimDocument>
 <FileVersion>1</FileVersion>
 <DesignInformation>
  <RocketDesign>
   <Name></Name>
   <CalculateCD>1</CalculateCD>
   <FixedCd>0.75</FixedCd>
   <StageCount>1</StageCount>
   <Stage3Mass>0.</Stage3Mass>
   <Stage2Mass>0.</Stage2Mass>
   <Stage1Mass>0.</Stage1Mass>
   <Stage321CG>0.</Stage321CG>
   <Stage32CG>0.</Stage32CG>
   <Stage3CG>0.</Stage3CG>
   <CPCalcFlags>1</CPCalcFlags>
   <LaunchGuideLength>914.4</LaunchGuideLength>
   <UseKnownMass>0</UseKnownMass>
   <DefaultFinish>1</DefaultFinish>
   <FinishMedium>0</FinishMedium>
   <FinishCoatCount>2</FinishCoatCount>
   <GlueType>0</GlueType>
   <Comments></Comments>
   <Designer></Designer>
   <CPSimFlags>1</CPSimFlags>
   <LastSerialNumber>14</LastSerialNumber>
   <DisplayFlags>0</DisplayFlags>
   <MetricsFlags>0</MetricsFlags>
   <CameraState></CameraState>
   <BarromanXN>0.,907.551051167349,0.,0.</BarromanXN>
   <BarrowmanCNa>0.,20.6279082737247,0.,0.</BarrowmanCNa>
   <RockSimXN>0.,926.649526620067,0.,0.</RockSimXN>
   <RockSimCNa>0.,25.9841049530833,0.,0.</RockSimCNa>
   <SimulationEventList>
   </SimulationEventList>
   <Stage3Parts>
    <NoseCone>
     <PartMfg>Aerotech</PartMfg>
     <KnownMass>48.194</KnownMass>
     <Density>1049.2093265</Density>
     <Material>Polystyrene PS</Material>
     <Name>Nose cone</Name>
     <KnownCG>152.4</KnownCG>
     <UseKnownCG>1</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>105.840149861269</CalcMass>
     <CalcCG>190.630646739664</CalcCG>
     <WettedSurface>2.45355041536372e-002</WettedSurface>
     <PaintedSurface>2.45355041536372e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>Aerotech</PartNo>
     <PartDesc>1.9NC</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>1</SerialNo>
     <DisplayFlags>0</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>2.</BarrowmanCNa>
     <BarrowmanXN>0.112239582036166</BarrowmanXN>
     <RockSimCNa>2.</RockSimCNa>
     <RockSimXN>0.112239582036166</RockSimXN>
     <Len>241.3</Len>
     <BaseDia>48.26</BaseDia>
     <FinishCode>1</FinishCode>
     <ShapeCode>1</ShapeCode>
     <ConstructionType>1</ConstructionType>
     <ShoulderLen>63.5</ShoulderLen>
     <WallThickness>3.18</WallThickness>
     <ShapeParameter>0.</ShapeParameter>
     <ShoulderOD>45.09</ShoulderOD>
     <PointList></PointList>
     <BaseExtensionLen>0.</BaseExtensionLen>
     <CoreDia>0.</CoreDia>
     <CoreLen>0.</CoreLen>
     <AttachedParts>
     </AttachedParts>
    </NoseCone>
    <BodyTube>
     <PartMfg>AreoTech</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>688.793909</Density>
     <Material>Cardboard</Material>
     <Name></Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>11.5715081080822</CalcMass>
     <CalcCG>115.</CalcCG>
     <WettedSurface>3.396061658974e-002</WettedSurface>
     <PaintedSurface>3.396061658974e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>11909</PartNo>
     <PartDesc>Tomahawk Lower Upper Tube</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>2</SerialNo>
     <DisplayFlags>0</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <OD>47.</OD>
     <ID>46.</ID>
     <Len>230.</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>12.7</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <Ring>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>688.793909</Density>
       <Material>Cardboard</Material>
       <Name>Tube coupler</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>181.4</Xb>
       <CalcMass>4.92289498754313</CalcMass>
       <CalcCG>50.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>3</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <OD>46.</OD>
       <ID>45.</ID>
       <Len>100.</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>4</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <Ring>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>1199.7828787</Density>
       <Material>Polycarbonate</Material>
       <Name>Bulkhead</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>181.4</Xb>
       <CalcMass>0.257249884581614</CalcMass>
       <CalcCG>1.5</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>4</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <OD>46.</OD>
       <ID>45.</ID>
       <Len>3.</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>1</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
     </AttachedParts>
    </BodyTube>
    <BodyTube>
     <PartMfg>AreoTech</PartMfg>
     <KnownMass>0.</KnownMass>
     <Density>688.793909</Density>
     <Material>Cardboard</Material>
     <Name>Body tube</Name>
     <KnownCG>0.</KnownCG>
     <UseKnownCG>0</UseKnownCG>
     <Xb>0.</Xb>
     <CalcMass>29.1803247942942</CalcMass>
     <CalcCG>290.</CalcCG>
     <WettedSurface>8.563981574804e-002</WettedSurface>
     <PaintedSurface>8.563981574804e-002</PaintedSurface>
     <GlueJointLength>0.</GlueJointLength>
     <DensityType>0</DensityType>
     <PartNo>11923</PartNo>
     <PartDesc>Tomahawk Lower body tube</PartDesc>
     <RadialLoc>0.</RadialLoc>
     <RadialAngle>0.</RadialAngle>
     <Texture></Texture>
     <Opacity>1.</Opacity>
     <Specular>0.</Specular>
     <SpecularPower>1.</SpecularPower>
     <Ambient>0.</Ambient>
     <Diffuse>1.</Diffuse>
     <AbientColor>0,0,250</AbientColor>
     <DiffuseColor>0,0,250</DiffuseColor>
     <SpecularColor>255,255,255</SpecularColor>
     <UseSingleColor>1</UseSingleColor>
     <SerialNo>5</SerialNo>
     <DisplayFlags>0</DisplayFlags>
     <MetricsFlags>0</MetricsFlags>
     <LocationMode>0</LocationMode>
     <Color>0,0,250</Color>
     <BarrowmanCNa>0.</BarrowmanCNa>
     <BarrowmanXN>0.</BarrowmanXN>
     <RockSimCNa>0.</RockSimCNa>
     <RockSimXN>0.</RockSimXN>
     <OD>47.</OD>
     <ID>46.</ID>
     <Len>580.</Len>
     <FinishCode>1</FinishCode>
     <IsMotorMount>0</IsMotorMount>
     <MotorDia>0.</MotorDia>
     <EngineOverhang>12.7</EngineOverhang>
     <FrontExtension>0.</FrontExtension>
     <RearExtension>0.</RearExtension>
     <IsInsideTube>0</IsInsideTube>
     <AttachedParts>
      <CustomFinSet>
       <PartMfg>AreoTech</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>128.147704</Density>
       <Material>Steel</Material>
       <Name>Custom Fin set</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>457.7</Xb>
       <CalcMass>10.7866781375456</CalcMass>
       <CalcCG>84.6670929444775</CalcCG>
       <WettedSurface>1.32557152212389e-002</WettedSurface>
       <PaintedSurface>5.30228608849558e-002</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo>11714</PartNo>
       <PartDesc>Tomahawk Fins</PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>6</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>18.6279082737247</BarrowmanCNa>
       <BarrowmanXN>0.992940291595701</BarrowmanXN>
       <RockSimCNa>23.9841049530833</RockSimCNa>
       <RockSimXN>0.994562</RockSimXN>
       <FinCount>4</FinCount>
       <RootChord>1828.8</RootChord>
       <TipChord>1828.8</TipChord>
       <SemiSpan>304.8</SemiSpan>
       <MidChordLen>1828.8</MidChordLen>
       <SweepDistance>0.0</SweepDistance>
       <Thickness>2.527</Thickness>
       <ShapeCode>2</ShapeCode>
       <FinishCode>1</FinishCode>
       <TipShapeCode>2</TipShapeCode>
       <TabLength>0.</TabLength>
       <TabDepth>0.</TabDepth>
       <TabOffset>0.</TabOffset>
       <SweepMode>0</SweepMode>
       <SweepAngle>0.9</SweepAngle>
       <AverageChord>89.47</AverageChord>
       <EffectiveTipChord>47.</EffectiveTipChord>
       <PointList>113.573628318584,0.|134.,9.|134.,74.|87.2619469026549,74.4846017699115|0.,0.</PointList>
       <AttachedParts>
       </AttachedParts>
      </CustomFinSet>
      <BodyTube>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>688.793909</Density>
       <Material>Cardboard</Material>
       <Name>engine tube</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>270.6</Xb>
       <CalcMass>8.08490830646509</CalcMass>
       <CalcCG>152.5</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>7</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <OD>25.</OD>
       <ID>24.</ID>
       <Len>305.</Len>
       <FinishCode>1</FinishCode>
       <IsMotorMount>1</IsMotorMount>
       <MotorDia>24.</MotorDia>
       <EngineOverhang>12.7</EngineOverhang>
       <FrontExtension>0.</FrontExtension>
       <RearExtension>0.</RearExtension>
       <IsInsideTube>1</IsInsideTube>
       <AttachedParts>
        <MassObject>
         <PartMfg>Estes</PartMfg>
         <KnownMass>1.4</KnownMass>
         <Density>0.</Density>
         <Material></Material>
         <Name>Engine hook</Name>
         <KnownCG>0.</KnownCG>
         <UseKnownCG>1</UseKnownCG>
         <Xb>267.8</Xb>
         <CalcMass>0.</CalcMass>
         <CalcCG>0.</CalcCG>
         <WettedSurface>0.</WettedSurface>
         <PaintedSurface>0.</PaintedSurface>
         <GlueJointLength>0.</GlueJointLength>
         <DensityType>0</DensityType>
         <PartNo>Engine hook</PartNo>
         <PartDesc>Standard size</PartDesc>
         <RadialLoc>0.</RadialLoc>
         <RadialAngle>0.</RadialAngle>
         <Texture></Texture>
         <Opacity>1.</Opacity>
         <Specular>0.</Specular>
         <SpecularPower>1.</SpecularPower>
         <Ambient>0.</Ambient>
         <Diffuse>1.</Diffuse>
         <AbientColor>0,0,250</AbientColor>
         <DiffuseColor>0,0,250</DiffuseColor>
         <SpecularColor>255,255,255</SpecularColor>
         <UseSingleColor>1</UseSingleColor>
         <SerialNo>10</SerialNo>
         <DisplayFlags>0</DisplayFlags>
         <MetricsFlags>0</MetricsFlags>
         <LocationMode>0</LocationMode>
         <Color>0,0,250</Color>
         <BarrowmanCNa>0.</BarrowmanCNa>
         <BarrowmanXN>0.</BarrowmanXN>
         <RockSimCNa>0.</RockSimCNa>
         <RockSimXN>0.</RockSimXN>
         <TypeCode>0</TypeCode>
         <Len>0.</Len>
         <AttachedParts>
         </AttachedParts>
        </MassObject>
        <MassObject>
         <PartMfg>AeroTech</PartMfg>
         <KnownMass>3.8</KnownMass>
         <Density>0.</Density>
         <Material></Material>
         <Name>Screw Eye</Name>
         <KnownCG>0.</KnownCG>
         <UseKnownCG>1</UseKnownCG>
         <Xb>14.9</Xb>
         <CalcMass>0.</CalcMass>
         <CalcCG>0.</CalcCG>
         <WettedSurface>0.</WettedSurface>
         <PaintedSurface>0.</PaintedSurface>
         <GlueJointLength>0.</GlueJointLength>
         <DensityType>0</DensityType>
         <PartNo>19015</PartNo>
         <PartDesc>Screw Eye</PartDesc>
         <RadialLoc>0.</RadialLoc>
         <RadialAngle>0.</RadialAngle>
         <Texture></Texture>
         <Opacity>1.</Opacity>
         <Specular>0.</Specular>
         <SpecularPower>1.</SpecularPower>
         <Ambient>0.</Ambient>
         <Diffuse>1.</Diffuse>
         <AbientColor>0,0,250</AbientColor>
         <DiffuseColor>0,0,250</DiffuseColor>
         <SpecularColor>255,255,255</SpecularColor>
         <UseSingleColor>1</UseSingleColor>
         <SerialNo>11</SerialNo>
         <DisplayFlags>0</DisplayFlags>
         <MetricsFlags>0</MetricsFlags>
         <LocationMode>0</LocationMode>
         <Color>0,0,250</Color>
         <BarrowmanCNa>0.</BarrowmanCNa>
         <BarrowmanXN>0.</BarrowmanXN>
         <RockSimCNa>0.</RockSimCNa>
         <RockSimXN>0.</RockSimXN>
         <TypeCode>0</TypeCode>
         <Len>0.</Len>
         <AttachedParts>
         </AttachedParts>
        </MassObject>
        <MassObject>
         <PartMfg>AeroTech</PartMfg>
         <KnownMass>0.</KnownMass>
         <Density>0.</Density>
         <Material>1/4 In. flat elastic</Material>
         <Name>Shock Cord</Name>
         <KnownCG>0.</KnownCG>
         <UseKnownCG>1</UseKnownCG>
         <Xb>9.9</Xb>
         <CalcMass>0.</CalcMass>
         <CalcCG>0.</CalcCG>
         <WettedSurface>0.</WettedSurface>
         <PaintedSurface>0.</PaintedSurface>
         <GlueJointLength>0.</GlueJointLength>
         <DensityType>0</DensityType>
         <PartNo>17388</PartNo>
         <PartDesc>Shock cord</PartDesc>
         <RadialLoc>0.</RadialLoc>
         <RadialAngle>0.</RadialAngle>
         <Texture></Texture>
         <Opacity>1.</Opacity>
         <Specular>0.</Specular>
         <SpecularPower>1.</SpecularPower>
         <Ambient>0.</Ambient>
         <Diffuse>1.</Diffuse>
         <AbientColor>0,0,250</AbientColor>
         <DiffuseColor>0,0,250</DiffuseColor>
         <SpecularColor>255,255,255</SpecularColor>
         <UseSingleColor>1</UseSingleColor>
         <SerialNo>12</SerialNo>
         <DisplayFlags>0</DisplayFlags>
         <MetricsFlags>0</MetricsFlags>
         <LocationMode>0</LocationMode>
         <Color>0,0,250</Color>
         <BarrowmanCNa>0.</BarrowmanCNa>
         <BarrowmanXN>0.</BarrowmanXN>
         <RockSimCNa>0.</RockSimCNa>
         <RockSimXN>0.</RockSimXN>
         <TypeCode>1</TypeCode>
         <Len>24.</Len>
         <AttachedParts>
         </AttachedParts>
        </MassObject>
        <MassObject>
         <PartMfg>Custom</PartMfg>
         <KnownMass>2.</KnownMass>
         <Density>0.</Density>
         <Material></Material>
         <Name>ejection gas baffle</Name>
         <KnownCG>0.</KnownCG>
         <UseKnownCG>1</UseKnownCG>
         <Xb>44.6</Xb>
         <CalcMass>0.</CalcMass>
         <CalcCG>0.</CalcCG>
         <WettedSurface>0.</WettedSurface>
         <PaintedSurface>0.</PaintedSurface>
         <GlueJointLength>0.</GlueJointLength>
         <DensityType>0</DensityType>
         <PartNo></PartNo>
         <PartDesc></PartDesc>
         <RadialLoc>0.</RadialLoc>
         <RadialAngle>0.</RadialAngle>
         <Texture></Texture>
         <Opacity>1.</Opacity>
         <Specular>0.</Specular>
         <SpecularPower>1.</SpecularPower>
         <Ambient>0.</Ambient>
         <Diffuse>1.</Diffuse>
         <AbientColor>0,0,250</AbientColor>
         <DiffuseColor>0,0,250</DiffuseColor>
         <SpecularColor>255,255,255</SpecularColor>
         <UseSingleColor>1</UseSingleColor>
         <SerialNo>13</SerialNo>
         <DisplayFlags>0</DisplayFlags>
         <MetricsFlags>0</MetricsFlags>
         <LocationMode>0</LocationMode>
         <Color>0,0,250</Color>
         <BarrowmanCNa>0.</BarrowmanCNa>
         <BarrowmanXN>0.</BarrowmanXN>
         <RockSimCNa>0.</RockSimCNa>
         <RockSimXN>0.</RockSimXN>
         <TypeCode>0</TypeCode>
         <Len>0.</Len>
         <AttachedParts>
         </AttachedParts>
        </MassObject>
        <Parachute>
         <PartMfg>LOC</PartMfg>
         <KnownMass>10.06</KnownMass>
         <Density>6.685e-003</Density>
         <Material>Rip stop nylon</Material>
         <Name>Parachute</Name>
         <KnownCG>0.</KnownCG>
         <UseKnownCG>1</UseKnownCG>
         <Xb>0.</Xb>
         <CalcMass>6.28309282122936</CalcMass>
         <CalcCG>30.6916666666667</CalcCG>
         <WettedSurface>0.</WettedSurface>
         <PaintedSurface>0.</PaintedSurface>
         <GlueJointLength>0.</GlueJointLength>
         <DensityType>1</DensityType>
         <PartNo>14 1/2 in.</PartNo>
         <PartDesc>Nylon 14 in.</PartDesc>
         <RadialLoc>0.</RadialLoc>
         <RadialAngle>0.</RadialAngle>
         <Texture></Texture>
         <Opacity>1.</Opacity>
         <Specular>0.</Specular>
         <SpecularPower>1.</SpecularPower>
         <Ambient>0.</Ambient>
         <Diffuse>1.</Diffuse>
         <AbientColor>0,0,250</AbientColor>
         <DiffuseColor>0,0,250</DiffuseColor>
         <SpecularColor>255,255,255</SpecularColor>
         <UseSingleColor>1</UseSingleColor>
         <SerialNo>14</SerialNo>
         <DisplayFlags>0</DisplayFlags>
         <MetricsFlags>0</MetricsFlags>
         <LocationMode>0</LocationMode>
         <Color>0,0,250</Color>
         <BarrowmanCNa>0.</BarrowmanCNa>
         <BarrowmanXN>0.</BarrowmanXN>
         <RockSimCNa>0.</RockSimCNa>
         <RockSimXN>0.</RockSimXN>
         <Dia>368.3</Dia>
         <SpillHoleDia>0.</SpillHoleDia>
         <SideCount>6</SideCount>
         <ShroudLineCount>6</ShroudLineCount>
         <Thickness>0.</Thickness>
         <ShroudLineLen>368.3</ShroudLineLen>
         <ChuteCount>1</ChuteCount>
         <ShroudLineMassPerMM>1.78e-004</ShroudLineMassPerMM>
         <ShroudLineMaterial>30 Lb. kevlar</ShroudLineMaterial>
         <DragCoefficient>0.75</DragCoefficient>
         <AttachedParts>
         </AttachedParts>
        </Parachute>
       </AttachedParts>
      </BodyTube>
      <Ring>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>1218.</Density>
       <Material>Lexan</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>340.</Xb>
       <CalcMass>2.85262582009243</CalcMass>
       <CalcCG>1.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>8</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <OD>46.</OD>
       <ID>25.</ID>
       <Len>2.</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
      <Ring>
       <PartMfg>Custom</PartMfg>
       <KnownMass>0.</KnownMass>
       <Density>1218.</Density>
       <Material>Lexan</Material>
       <Name>Ring</Name>
       <KnownCG>0.</KnownCG>
       <UseKnownCG>0</UseKnownCG>
       <Xb>540.9</Xb>
       <CalcMass>2.85262582009243</CalcMass>
       <CalcCG>1.</CalcCG>
       <WettedSurface>0.</WettedSurface>
       <PaintedSurface>0.</PaintedSurface>
       <GlueJointLength>0.</GlueJointLength>
       <DensityType>0</DensityType>
       <PartNo></PartNo>
       <PartDesc></PartDesc>
       <RadialLoc>0.</RadialLoc>
       <RadialAngle>0.</RadialAngle>
       <Texture></Texture>
       <Opacity>1.</Opacity>
       <Specular>0.</Specular>
       <SpecularPower>1.</SpecularPower>
       <Ambient>0.</Ambient>
       <Diffuse>1.</Diffuse>
       <AbientColor>0,0,250</AbientColor>
       <DiffuseColor>0,0,250</DiffuseColor>
       <SpecularColor>255,255,255</SpecularColor>
       <UseSingleColor>1</UseSingleColor>
       <SerialNo>9</SerialNo>
       <DisplayFlags>0</DisplayFlags>
       <MetricsFlags>0</MetricsFlags>
       <LocationMode>0</LocationMode>
       <Color>0,0,250</Color>
       <BarrowmanCNa>0.</BarrowmanCNa>
       <BarrowmanXN>0.</BarrowmanXN>
       <RockSimCNa>0.</RockSimCNa>
       <RockSimXN>0.</RockSimXN>
       <OD>46.</OD>
       <ID>25.</ID>
       <Len>2.</Len>
       <FinishCode>0</FinishCode>
       <UsageCode>0</UsageCode>
       <AutoSize>1</AutoSize>
       <AttachedParts>
       </AttachedParts>
      </Ring>
     </AttachedParts>
    </BodyTube>
   </Stage3Parts>
   <Stage2Parts>
   </Stage2Parts>
   <Stage1Parts>
   </Stage1Parts>
  </RocketDesign>
 </DesignInformation>
 <SimulationResultsList>
  <SimulationResults>
   <MaxAltitude>470.426961843702</MaxAltitude>
   <MaxVelocity>195.597336407942</MaxVelocity>
   <MaxAcceleration>290.003257409002</MaxAcceleration>
   <TimeToApogee>7.94100000000099</TimeToApogee>
   <OptimalDelay>7.14100000000099</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>24.5866254376589,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>433.727646624016,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>10.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>10.8009999999995,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>2</FinalState>
   <TimeToBurnout>0.800000000000001</TimeToBurnout>
   <TimeToLanding>1.88568365189093e-094</TimeToLanding>
   <TimeToEject>10.8009999999995</TimeToEject>
   <MinLaunchGuideLen>0.379358332186451</MinLaunchGuideLen>
   <MaxVertVelocity>195.597336407942</MaxVertVelocity>
   <MaxHorzVelocity>0.</MaxHorzVelocity>
   <MaxVertAcceleration>290.003257409002</MaxVertAcceleration>
   <MaxHorzAcceleration>0.</MaxHorzAcceleration>
   <MaxRange>0.</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchBarometer>759.968</LaunchBarometer>
   <LaunchLatitude>45.</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>25.</LaunchTemperature>
   <LaunchAltitude>0.</LaunchAltitude>
   <SimulationName>[E50-10] </SimulationName>
   <VelocityAtLaunchGuideEnd>21.7864543667312</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>0.108</TimeToFreeFlight>
   <TimeToMaxVelocity>0.794000000000001</TimeToMaxVelocity>
   <TimeToMaxAcceleration>0.4</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>earth</LocationDatabaseDisplayName>
   <ExecutionTime>0.</ExecutionTime>
   <RangeAtLanding>0.</RangeAtLanding>
   <VelocityAtLanding>0.</VelocityAtLanding>
   <XVelcoityAtLanding>0.</XVelcoityAtLanding>
   <YVelocityAtLanding>0.</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,0.</TimeToDeployment>
   <DeploymentType>32,32,32</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>E50</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg></EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>-1</MountSerialNo>
     <EjectionDelay>10.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>921.025515290897</MaxAltitude>
   <MaxVelocity>281.175186283036</MaxVelocity>
   <MaxAcceleration>460.08578558389</MaxAcceleration>
   <TimeToApogee>9.88399999999996</TimeToApogee>
   <OptimalDelay>7.70300000000009</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>20.3906583698029,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>896.72229006392,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>10.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>12.1809999999987,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>2</FinalState>
   <TimeToBurnout>2.18099999999987</TimeToBurnout>
   <TimeToLanding>0.</TimeToLanding>
   <TimeToEject>12.1809999999987</TimeToEject>
   <MinLaunchGuideLen>0.260534943067403</MinLaunchGuideLen>
   <MaxVertVelocity>281.175186283036</MaxVertVelocity>
   <MaxHorzVelocity>0.</MaxHorzVelocity>
   <MaxVertAcceleration>460.08578558389</MaxVertAcceleration>
   <MaxHorzAcceleration>0.</MaxHorzAcceleration>
   <MaxRange>0.</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>0.</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>0.</LaunchAngle>
   <LaunchBarometer>759.968</LaunchBarometer>
   <LaunchLatitude>45.</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>25.</LaunchTemperature>
   <LaunchAltitude>0.</LaunchAltitude>
   <SimulationName>[G55-10] </SimulationName>
   <VelocityAtLaunchGuideEnd>27.7807089353337</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>8.80000000000001e-002</TimeToFreeFlight>
   <TimeToMaxVelocity>1.16099999999998</TimeToMaxVelocity>
   <TimeToMaxAcceleration>0.2</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>earth</LocationDatabaseDisplayName>
   <ExecutionTime>0.</ExecutionTime>
   <RangeAtLanding>0.</RangeAtLanding>
   <VelocityAtLanding>0.</VelocityAtLanding>
   <XVelcoityAtLanding>0.</XVelcoityAtLanding>
   <YVelocityAtLanding>0.</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,0.</TimeToDeployment>
   <DeploymentType>32,32,32</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>G55</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg></EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>-1</MountSerialNo>
     <EjectionDelay>10.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>755.885944882991</MaxAltitude>
   <MaxVelocity>250.638994178035</MaxVelocity>
   <MaxAcceleration>288.53086274801</MaxAcceleration>
   <TimeToApogee>9.34800000000026</TimeToApogee>
   <OptimalDelay>7.24700000000038</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>38.0407375543005,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>657.778262856701,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>12.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>14.1009999999976,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>2</FinalState>
   <TimeToBurnout>2.10099999999988</TimeToBurnout>
   <TimeToLanding>1.90354922148613e+185</TimeToLanding>
   <TimeToEject>14.1009999999976</TimeToEject>
   <MinLaunchGuideLen>0.346506933388702</MinLaunchGuideLen>
   <MaxVertVelocity>248.850287945408</MaxVertVelocity>
   <MaxHorzVelocity>29.9052831227886</MaxHorzVelocity>
   <MaxVertAcceleration>283.856118066478</MaxVertAcceleration>
   <MaxHorzAcceleration>51.7277777827413</MaxHorzAcceleration>
   <MaxRange>167.185631075873</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>2.78</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>10.</LaunchAngle>
   <LaunchBarometer>759.97</LaunchBarometer>
   <LaunchLatitude>45.</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>15.6</LaunchTemperature>
   <LaunchAltitude>28.</LaunchAltitude>
   <SimulationName>[G42-12] </SimulationName>
   <VelocityAtLaunchGuideEnd>22.8001884148686</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>9.30000000000001e-002</TimeToFreeFlight>
   <TimeToMaxVelocity>1.32699999999996</TimeToMaxVelocity>
   <TimeToMaxAcceleration>0.1</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>earth</LocationDatabaseDisplayName>
   <ExecutionTime>0.</ExecutionTime>
   <RangeAtLanding>0.</RangeAtLanding>
   <VelocityAtLanding>0.</VelocityAtLanding>
   <XVelcoityAtLanding>0.</XVelcoityAtLanding>
   <YVelocityAtLanding>0.</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,0.</TimeToDeployment>
   <DeploymentType>32,32,32</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>G42</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg></EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>-1</MountSerialNo>
     <EjectionDelay>12.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
  <SimulationResults>
   <MaxAltitude>755.885944882991</MaxAltitude>
   <MaxVelocity>250.638994178035</MaxVelocity>
   <MaxAcceleration>288.53086274801</MaxAcceleration>
   <TimeToApogee>9.34800000000026</TimeToApogee>
   <OptimalDelay>7.24700000000038</OptimalDelay>
   <MultiDelayCount>1</MultiDelayCount>
   <VelocityAtDeplyment>38.0407375543005,0.,0.,0.,0.,0.,0.,0.,0.,0.</VelocityAtDeplyment>
   <AltitudeAtDeployment>657.778262856701,0.,0.,0.,0.,0.,0.,0.,0.,0.</AltitudeAtDeployment>
   <DelayTime>12.,0.,0.,0.,0.,0.,0.,0.,0.,0.</DelayTime>
   <EjectTime>14.1009999999976,0.,0.,0.,0.,0.,0.,0.,0.,0.</EjectTime>
   <FinalState>2</FinalState>
   <TimeToBurnout>2.10099999999988</TimeToBurnout>
   <TimeToLanding>0.</TimeToLanding>
   <TimeToEject>14.1009999999976</TimeToEject>
   <MinLaunchGuideLen>0.346506933388702</MinLaunchGuideLen>
   <MaxVertVelocity>248.850287945408</MaxVertVelocity>
   <MaxHorzVelocity>29.9052831227886</MaxHorzVelocity>
   <MaxVertAcceleration>283.856118066478</MaxVertAcceleration>
   <MaxHorzAcceleration>51.7277777827413</MaxHorzAcceleration>
   <MaxRange>167.185631075873</MaxRange>
   <LaunchWindDirection>0</LaunchWindDirection>
   <LaunchWindSpeed>2.78</LaunchWindSpeed>
   <LaunchDirection>0</LaunchDirection>
   <LaunchAngle>10.</LaunchAngle>
   <LaunchBarometer>759.97</LaunchBarometer>
   <LaunchLatitude>45.</LaunchLatitude>
   <LaunchHumidity>50.</LaunchHumidity>
   <LaunchTemperature>15.6</LaunchTemperature>
   <LaunchAltitude>28.</LaunchAltitude>
   <SimulationName>[G42-12] </SimulationName>
   <VelocityAtLaunchGuideEnd>22.8001884148686</VelocityAtLaunchGuideEnd>
   <LaunchGuideLen>0.9144</LaunchGuideLen>
   <WindStartAltitude>0.</WindStartAltitude>
   <Comments></Comments>
   <TimeToWindShear>0.</TimeToWindShear>
   <TimeToFreeFlight>9.30000000000001e-002</TimeToFreeFlight>
   <TimeToMaxVelocity>1.32699999999996</TimeToMaxVelocity>
   <TimeToMaxAcceleration>0.1</TimeToMaxAcceleration>
   <SamplesPerSecond>1000</SamplesPerSecond>
   <SimulationType>0</SimulationType>
   <LocationDatabaseName>earth</LocationDatabaseName>
   <LocationDatabaseDisplayName>earth</LocationDatabaseDisplayName>
   <ExecutionTime>0.</ExecutionTime>
   <RangeAtLanding>0.</RangeAtLanding>
   <VelocityAtLanding>0.</VelocityAtLanding>
   <XVelcoityAtLanding>0.</XVelcoityAtLanding>
   <YVelocityAtLanding>0.</YVelocityAtLanding>
   <StageEjectTime>0.,0.,0.</StageEjectTime>
   <TimeToDeployment>0.,0.,0.</TimeToDeployment>
   <DeploymentType>32,32,32</DeploymentType>
   <SamplesPerSecondDescent>10</SamplesPerSecondDescent>
   <CalculationFlags>1</CalculationFlags>
   <Mass0>0.</Mass0>
   <CG0>0.</CG0>
   <LaterialMOI0>0.</LaterialMOI0>
   <RadialMOI0>0.</RadialMOI0>
   <SimulationEvents>
   </SimulationEvents>
   <Stage1Engines>
   </Stage1Engines>
   <Stage2Engines>
   </Stage2Engines>
   <Stage3Engines>
    <EngineSet>
     <EngineCount>1</EngineCount>
     <EngineCode>G42</EngineCode>
     <IgnitionDelay>0.</IgnitionDelay>
     <EngineMfg></EngineMfg>
     <EngineOverhang>12.7</EngineOverhang>
     <CasingCG>0.</CasingCG>
     <MountSerialNo>-1</MountSerialNo>
     <EjectionDelay>12.</EjectionDelay>
    </EngineSet>
   </Stage3Engines>
  </SimulationResults>
 </SimulationResultsList>
</RockSimDocument>
